name: 'GPTReview'
description: 'Let AI review your code'
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install
        run: |
          sudo apt-get update
          python3 -m venv .env
          source .env/bin/activate
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Review PR and make comment
        run: |
          source .env/bin/activate
          python review.py
        env:
          LINK: "https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          GIT_COMMIT_HASH: ${{ github.sha }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}