name: Review PR with OpenAI GPT model

on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    name: Review PR
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo PR Link
      - run: |
        echo ${{ github.event.pull_request.html_url }}

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # install the python version needed
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set the value
        run: |
          echo "COMMENT=$(python review.py)" >> $GITHUB_ENV

      # Add the uses key to the action step
      - uses: thollander/actions-comment-pull-request@v1
        with:
          message: ${{ env.COMMENT }}
