name: Review PR with OpenAI GPT model

on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    name: Review PR
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install
        run: |
          sudo apt-get update
          python3 -m venv .env
          source .env/bin/activate
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Set link, api key, and get comment
        run: |
          curl https://api.openai.com/v1/completions \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}' \
          -d '{
          "model": "text-davinci-003",
          "prompt": "Say this is a test",
          "max_tokens": 7,
          "temperature": 0
        }'


