on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test if the action works
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: samjhill/GPTReview@main
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_COMMIT_HASH: ${{ secrets.GIT_COMMIT_HASH }}
          PR_TITLE: ${{ secrets.PR_TITLE }}
          PR_BODY: ${{ secrets.PR_BODY }}
          REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
          PR_NUMBER: ${{ secrets.PR_NUMBER }}
