name: Comment on PR

on:
  issue_comment:
    types: [created]

env:
  COMMENT: "hi there"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Add the uses key to the action step
      - uses: thollander/actions-comment-pull-request@v1
        with:
          comment: ${{ env.COMMENT }}
