name: Comment on PR

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: thollander/actions-comment-pull-request@v1
        with:
          # Set the comment to the comment author's name
          comment: ${{ github.actor }}
