on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test if the action works
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: samjhill/GPTReview@main
