name: Comment on PR

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        run: |
          echo "COMMENT=hi" >> $GITHUB_ENV
      # Add the uses key to the action step
      - uses: thollander/actions-comment-pull-request@v1
        with:
          comment: ${{ env.COMMENT }}
